# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.mail_from: 'noreply@santa.local'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\AppMailer:
        arguments:
            $mailFrom: '%app.mail_from%'
